import dotenv from "dotenv";
import mongoose from "mongoose";
import Course from "../models/Course.js";

dotenv.config({ path: new URL("../.env", import.meta.url).pathname });

async function main() {
  const uri = process.env.MONGO_URI;
  if (!uri) throw new Error("Falta MONGO_URI en .env");

  await mongoose.connect(uri);
  console.log("✅ Conectado a Mongo para seed");

  const data = [
    {
      slug: "comunicacion",
      kind: "course",
      isArchive: false,
      title: "El Padre, el Árbol y el Maestro - Ger Páez",
      level: "free",
      short: "Fundamentos para una relación sana con Dios.",
      long:
        "¿Peleas con el pecado y ciclos que se repiten en el tiempo? ¿Sentís que estás atrapado y no podés salir? ¡El primer paso es ser hijos! Pero para ser hijos debemos ser estudiantes primero. El Padre busca un corazón dispuesto a aprender. Tanto un Padre, como un árbol y un maestro tienen en común que se reproducen y trascienden. Se replican en otros. Así es como El Padre quiere restaurar Su Imagen en nosotros nuevamente; enseñándonos. Aprende los fundamentos para desarrollar una relación sana con Dios y dar frutos en abundancia.",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/arbol.jpg",
      lessons: [
        { title: "Intro", videoUrl: "https://youtu.be/R_XP5HOfzxo" },
        { title: "Clase 1", videoUrl: "https://www.youtube.com/watch?v=tbbF_Y6qIQM" },
        { title: "Clase 2", videoUrl: "https://www.youtube.com/watch?v=yfLieVNSe4s" },
        { title: "Clase 3", videoUrl: "https://www.youtube.com/watch?v=5N6pPBhJy0I" },
      ],
      materials: [],
    },
    {
      slug: "pro-avanzado",
      kind: "course",
      isArchive: false,
      title: "Comunicación, tecnología y el plan de Dios - Ger Páez",
      level: "pro",
      short: "Ubicá la tecnología y las ideologías en el Plan de Dios.",
      long:
        "¿Te abruma el avance vertiginoso de la tecnología? ¿Te sentís confundido por los medios, las noticias y las ideologías? ¿Será que el antisemitisimo y el avance del Islam están ajenos a la agenda de Dios? ¿Qué hacemos con la IA? ¿Y la computación cuántica? Encontrá el lugar de la tecnología y las ideologías dentro del Plan de Dios, a Él no se le escapa nada y todo tiene un propósito dentro de Su voluntad. Aprende a entender los tiempos y a convertirte en una señal que apunte a Cristo en medio de la oscuridad. Isacar observaba estrellas para entender las temporadas ¿Qué observamos nosotros?",
      price: 35,
      currency: "USD",
      thumbnail: "/assets/cursos/tecnologia.jpg",
      lessons: [
        { title: "Intro", videoUrl: "https://www.youtube.com/watch?v=MBZR8MboWbE" },
        { title: "Clase 1", videoUrl: "https://www.youtube.com/watch?v=rbFUT_u-jFc" },
        { title: "Clase 2", videoUrl: "https://www.youtube.com/watch?v=0tgE0lPPO4o" },
      ],
      materials: [],
    },
    {
      slug: "renovacion-mente",
      kind: "course",
      isArchive: false,
      title: "Renovación de la Mente - Ger Páez",
      level: "pro",
      short: "Herramientas bíblicas prácticas para tu llamado.",
      long:
        "¿Te sentís dividido internamente? ¿Te cuesta conciliar tu llamado con tu trabajo o estudios? O incluso, ¿Tenés dificultades para entender qué es lo que Dios espera de vos? En este curso recibirás herramientas bíblicas practicas para renovar tu mente y, así, entender la buena, agradable y perfecta voluntad de Dios. Tenemos que salir del viejo paradigma caído y renovarnos a lo nuevo. Tenemos la mente de Cristo, ¡Desarrollémosla!",
      price: 35,
      currency: "USD",
      thumbnail: "/assets/cursos/renovacion.jpg",
      lessons: [
        { title: "Intro", videoUrl: "https://www.youtube.com/watch?v=Vgaolsn4cH8" },
        { title: "Clase 1", videoUrl: "https://www.youtube.com/watch?v=beIPGnOYIdQ" },
      ],
      materials: [],
    },
    {
      slug: "entendiendo-biblia",
      kind: "course",
      isArchive: false,
      title: "Entendiendo La Biblia - Ger Páez",
      level: "pro",
      short: "Un recorrido paso a paso para comprender la Biblia de manera integral.",
      long:
        "En este curso aprenderemos a abordar La Biblia como un todo, una narrativa única desde el principio hasta el final. 8 ejes temáticos desde Génesis hasta Apocalipsis, una sola historia: El Plan de Dios. Clase a clase profundizaremos en el Evangelio del Reino y adquiriremos la capacidad de entender los ejes temáticos de Las Escrituras, es decir, lo que Dios reitera una y otra vez sin parar hasta el final. El Mesías, el Anticristo, La Gran Tribulación, Israel, La Inclusión de los Gentiles, La Era Venidera (Milenio), Las Fiestas del Señor y La Resurrección y Reunión de los exiliados. ¿Qué es el evangelio del Reino? ¿De qué se compone? ¡Este curso es para vos!",
      price: 35,
      currency: "USD",
      thumbnail: "/assets/cursos/entendiendo.png",
      lessons: [
        { title: "Clase 1", videoUrl: "https://youtu.be/pwPqoKKq7wI?si=q-ezp-ua6_7pvrHJ" },
        { title: "Clase 2", videoUrl: "https://youtu.be/CNK5qAN6zgY?si=Z3iOBDZBa62DBfcb" },
        { title: "Clase 3", videoUrl: "https://youtu.be/QBL3hMQgADY?si=XV2SGhjv-mWdaygu" },
        { title: "Clase 4", videoUrl: "https://youtu.be/QBL3hMQgADY?si=d8EkLJtOPbwyZPQR" },
        { title: "Clase 5", videoUrl: "https://youtu.be/5vEaQc5cAv8?si=bbSou2xXzlXOe7G8" },
        { title: "Clase 6", videoUrl: "https://youtu.be/5L4WhR_VWLI?si=YR38Qk9pqiFdgBIB" },
        { title: "Clase 7", videoUrl: "https://youtu.be/aNLgiHSilgw?si=ICI2-nqFcwZpifEl" },
        { title: "Clase 8", videoUrl: "https://youtu.be/J7dEQ1B4Dk8?si=U_0bOmPEXCPdD2qG" },
      ],
      materials: [
        {
          title: "Clase 1 - ABC Bíblico",
          fileUrl: "/assets/cursos/entendiendo-biblia/clase1.pdf",
          type: "pdf",
        },
        {
          title: "Clase 2 - ABC Bíblico",
          fileUrl: "/assets/cursos/entendiendo-biblia/clase2.pdf",
          type: "pdf",
        },
        {
          title: "Clase 3 - ABC Bíblico",
          fileUrl: "/assets/cursos/entendiendo-biblia/clase3.pdf",
          type: "pdf",
        },
        {
          title: "Clase 4 - ABC Bíblico",
          fileUrl: "/assets/cursos/entendiendo-biblia/clase4.pdf",
          type: "pdf",
        },
        {
          title: "Clase 5 - ABC Bíblico",
          fileUrl: "/assets/cursos/entendiendo-biblia/clase5.pdf",
          type: "pdf",
        },
        {
          title: "Clase 6 - ABC Bíblico",
          fileUrl: "/assets/cursos/entendiendo-biblia/clase6.pdf",
          type: "pdf",
        },
        {
          title: "Clase 7 - ABC Bíblico",
          fileUrl: "/assets/cursos/entendiendo-biblia/clase7.pdf",
          type: "pdf",
        },
        {
          title: "Clase 8 - ABC Bíblico",
          fileUrl: "/assets/cursos/entendiendo-biblia/clase8.pdf",
          type: "pdf",
        },
        {
          title: "Del Sinaí A Sión",
          fileUrl: "/assets/cursos/entendiendo-biblia/libro1.pdf",
          type: "book",
        },
        {
          title: "El Anticristo Islámico - Joel Richardson",
          fileUrl: "/assets/cursos/entendiendo-biblia/libro2.pdf",
          type: "book",
        },
      ],
    },
    {
      slug: "masterclass-anatomia",
      kind: "masterclass",
      isArchive: false,
      title: "Anatomía de la Iglesia Gloriosa - Ger Páez",
      level: "free",
      short: "Una introducción para profundizar en la identidad de la Iglesia.",
      long:
        "¿Cómo es la Iglesia Gloriosa? A sabiendas de que la iglesia que vemos hoy es la materia prima de aquella Iglesia que resiste y persevera en el fin de la era, necesitamos profundizar en Las Escrituras para entender cómo ve Dios a la Iglesia. Israel, la unidad y otros temas esenciales forman parte del core de la Iglesia Gloriosa. Podrán decir al final: ¡Su novia se ha preparado!",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/anatomia.png",
      lessons: [{ title: "Masterclass", videoUrl: "https://youtu.be/GqvrOUwZXr0?si=3whl9Z5-tnvy7y0f" }],
      materials: [],
    },
    {
      slug: "masterclass-silencio",
      kind: "masterclass",
      isArchive: false,
      title: "El Silencio En El Discurso - Ger Páez",
      level: "free",
      short: "Dios nos muestra al silencio como la antesala de lo impresionante, el preludio de las maravillas.",
      long:
        "El silencio muchas veces es visto como ausencia, falta y pérdida. Escuchamos expresiones como hubo un silencio sepulcral e, inconscientemente, vinculamos al silencio incluso con la muerte. Bíblicamente esto no es estrictamente así. Dios nos muestra al silencio como la antesala de lo impresionante, el preludio de las maravillas. En nuestro discurso podemos utilizar el silencio como algo fantástico, un arte divino que, al ser imagen y semejanza del Dios eterno, tenemos a nuestra disposición. Selah.",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/silencio.png",
      lessons: [{ title: "Masterclass", videoUrl: "https://youtu.be/zKBEyiQxBik?si=D44ILsIJu70yB8X8" }],
      materials: [],
    },
    {
      slug: "masterclass-ecosistema-critica",
      kind: "masterclass",
      isArchive: false,
      title: "Ecosistema de Crítica - Ger Páez",
      level: "free",
      short: "¡Descubramos todas las bondades de dar y aceptar crítica!",
      long:
        "Generalmente demonizamos la crítica, pero estamos firmemente comprometidos con la siguiente verdad: la crítica no es el problema; en realidad nos queremos referir a la murmuración. Crítica es de frente, en la mesa, con ánimo de desarrollar nuevas cosas. La murmuración ataca agazapada en lo oscuro de una conversación donde el criticado no está presente. ¡Descubramos todas las bondades de dar y aceptar crítica! La Biblia y el mismo Dios nos lo aconsejan.",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/ecosistema.png",
      lessons: [{ title: "Masterclass", videoUrl: "https://youtu.be/9bzzmBnFHIs?si=Q7v0two8ZC-bHWuE" }],
      materials: [],
    },
    {
      slug: "masterclass-antropocentrismo",
      kind: "masterclass",
      isArchive: false,
      title: "Antropocentrismo - Ger Páez",
      level: "free",
      short: "Del antropocentrismo al Cristo-centrismo.",
      long:
        "¿Es Dios el genio de la lámpara? ¿Existe Él para mí o yo para Él? Estas son preguntas interesantes a la hora de entender la renovación de la mente. Pasar de una existencia ombliguista en donde todo gira en torno a uno mismo a una vida que se centra en Dios y Su plan es, en esencia, el principio de renovar la mente. Entender por qué pienso como pienso es esencial para poder sacrificar correctamente lo viejo y abrazar con todo lo que somos la nueva naturaleza que es en Cristo Jesús. Del antropocentrismo al Cristo-centrismo.",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/antropocentrismo-general.png",
      lessons: [
        {
          title: "Parte 1",
          videoUrl: "https://youtu.be/rT1PZsqnbpU?si=SviRbzHcXCfO3AzR",
          thumbnail: "/assets/cursos/antropo.png",
        },
        {
          title: "Parte 2",
          videoUrl: "https://www.youtube.com/watch?v=jM8OO_ibeMI",
          thumbnail: "/assets/cursos/antropo2.png",
        },
      ],
      materials: [],
    },
    {
      slug: "masterclass-mente-dual",
      kind: "masterclass",
      isArchive: false,
      title: "Mente Dual vs Mente Escritural - Ger Páez",
      level: "free",
      short: "La mente de Cristo está en nosotros, ¡desarrollémosla!",
      long:
        "Peleamos internamente, diariamente. Creo, no creo. Amo, no amo. Tengo fuerza, no la tengo. Sube y baja. Doble ánimo. Mente partida. ¿Soy yo o le pasa a todos? Como occidentales heredamos el dualismo griego y está fusionado con nuestra mentalidad. Conforma nuestro paradigma y es, muchas veces, la lente con la que vemos la realidad; generalmente sin saberlo ni notarlo. Dios nos llama a renovar la mente a una mentalidad integrativa e integral; completa. La mente de Cristo está en nosotros, ¡desarrollémosla!",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/mentedual.png",
      lessons: [{ title: "Masterclass", videoUrl: "https://youtu.be/9lvh65VkfrQ?si=DolGHQ_X-xL_AH13" }],
      materials: [],
    },
    {
      slug: "masterclass-cv-entrevistas",
      kind: "masterclass",
      isArchive: false,
      title: "CV y Entrevistas - Araceli Montagano",
      level: "free",
      short: "Un espacio planteado para crecer y adquirir herramientas para nuestra vida profesional.",
      long:
        "¿Cómo armo un CV correctamente? ¿Cómo me comporto en una entrevista laboral? ¿Qué digo y qué no? Todo esto y mucho más en un espacio planteado para crecer y adquirir herramientas para nuestra vida profesional. Mansos como palomas, ¡pero también astutos como serpientes!",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/entrevistas.png",
      lessons: [{ title: "Masterclass", videoUrl: "https://youtu.be/UTmVS8Op_dA?si=fAT0i-Hc4jPQ4fy8" }],
      materials: [],
    },
    {
      slug: "masterclass-renovacion-mente",
      kind: "masterclass",
      isArchive: false,
      title: "Renovación de la Mente - Ger Páez",
      level: "free",
      short: "Una introducción a la renovación, la mentalidad y la transformación.",
      long:
        "Una masterclass gratuita para empezar a trabajar principios de renovación de la mente, transformación interior y alineación con la verdad de Dios.",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/renovacionn.png",
      lessons: [{ title: "Masterclass", videoUrl: "https://youtu.be/iWltoOn4BsA?si=7TEPy65oPhIrRcid" }],
      materials: [],
    },
    {
      slug: "masterclass-apocalipsis-islamico",
      kind: "masterclass",
      isArchive: false,
      title: "Apocalipsis Islámico - Ger Páez",
      level: "free",
      short: "Una mirada bíblica sobre el Islam y los últimos tiempos.",
      long:
        "La religión más prolífera de los últimos 100 años es el Islam. ¿Debería esto alarmarnos? ¿Llamarnos la atención? ¿La Biblia dice algo al respecto? Creemos que la respuesta a todo esto es ¡SÍ! El Islam tiene una esperanza MUY similar a la del cristianismo bíblico; esperan un mesías, y por separado a Jesús, que también dicen, descenderá del cielo. Pero Isa (como llama el islam Jesús) no es Dios, ni tampoco el Mesías en sí mismo, sino una especie de apoyo del Mahdi, el salvador islámico. Sin pivotear sobre el Corán, sino apoyados en la profecía bíblica, observamos los últimos tiempos según el Islam y reflexionamos sobre la posibilidad de un Anticristo Islámico.",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/apocalipsis.png",
      lessons: [{ title: "Masterclass", videoUrl: "https://www.youtube.com/watch?v=4bdV8DpniZ8" }],
      materials: [],
    },
    {
      slug: "archivo-masterclass-01",
      kind: "masterclass",
      isArchive: true,
      title: "Educación En Los Tiempos Del Fin - Emiliano Rodriguez",
      level: "free",
      short: "Familias saludables y rol de los padres en la educación de sus hijos",
      long: "Reflexionamos sobre la importancia de familias saludables y el rol de los padres en la educación de sus hijos. Escencialmente en la trascendencia y lo prioritario que es que los padres sean los que enseñen el plan de Dios a sus hijos.",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/educacion.png",
      lessons: [{ title: "Masterclass", videoUrl: "https://www.youtube.com/watch?v=qQy18CZwtJE" }],
      materials: [],
    },
    {
      slug: "archivo-masterclass-02",
      kind: "masterclass",
      isArchive: true,
      title: "La Ingenieria Del Control - Fabian Presas",
      level: "free",
      short: "La Bestia, Babilonia, Los Tiempos Finales...",
      long: "La Bestia, Babilonia, Los Tiempos Finales... Todo esto estará dispuesto en su momento, pero se desarrolla hoy. Profundizamos en como el control que veremos de mano del anticristo en el final de la era, ya se está construyendo hoy. ¿Cuál es nuestro rol entonces? ¿Qué podemos hacer como cuerpo de Cristo?",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/ingenieria.png",
      lessons: [{ title: "Masterclass", videoUrl: "https://www.youtube.com/watch?v=f38p_vqmHc0" }],
      materials: [],
    },
    {
      slug: "archivo-masterclass-03",
      kind: "masterclass",
      isArchive: true,
      title: "Rol De Los Profesionales · Parte 1 y 2 - Maxi Zeravika",
      level: "free",
      short: "Preparar el camino y colaborar con el Plan de Dios.",
      long: "Nos sumergimos en Las Escrituras para observar cuán importantes y vitales han sido los profesionales a través de la historia bíblica. También, vemos como hacia el final nuestras habilidades y capacidades técnicas son imprescindibles para preparar el camino y colaborar con el Plan de Dios.",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/rol.png",
      lessons: [
        { title: "Parte 1", videoUrl: "https://www.youtube.com/watch?v=9oMrVxcLl5w" },
        { title: "Parte 2", videoUrl: "https://www.youtube.com/watch?v=IJUEdgFXoo4" },
      ],
      materials: [],
    },
    {
      slug: "archivo-masterclass-04",
      kind: "masterclass",
      isArchive: true,
      title: "Rol De Los Profesionales · Parte 3 - Maxi Zeravika",
      level: "free",
      short: "Preparar el camino y colaborar con el Plan de Dios.",
      long: "Nos sumergimos en Las Escrituras para observar cuán importantes y vitales han sido los profesionales a través de la historia bíblica. También, vemos como hacia el final nuestras habilidades y capacidades técnicas son imprescindibles para preparar el camino y colaborar con el Plan de Dios.",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/rol2.png",
      lessons: [{ title: "Parte 3", videoUrl: "https://www.youtube.com/watch?v=PchZ08HGDRY" }],
      materials: [],
    },
    {
      slug: "archivo-masterclass-05",
      kind: "masterclass",
      isArchive: true,
      title: "Paternidad y Familia en los Últimos Tiempos - Ger Páez",
      level: "free",
      short: "Masterclass de años anteriores incorporada al archivo.",
      long: "Contenido de archivo disponible dentro de la biblioteca histórica de masterclasses.",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/paternidad.png",
      lessons: [{ title: "Masterclass", videoUrl: "https://www.youtube.com/watch?v=-BAa2E7NKrs" }],
      materials: [],
    },
    {
      slug: "archivo-masterclass-06",
      kind: "masterclass",
      isArchive: true,
      title: "La Redención del Tiempo y Su Venida - Fabian Presas",
      level: "free",
      short: "¿Cómo es el tiempo para Dios? ¿Qué ha establecido Él desde el principio?",
      long: "Nos detenemos en el tiempo. ¿Cómo es el tiempo para Dios? ¿Qué ha establecido Él desde el principio? ¿El tiempo de Su venida nos es completamente velado? ¡Las festividades y los tiempos señalados son desde Génesis 1!",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/redencion.png",
      lessons: [{ title: "Masterclass", videoUrl: "https://www.youtube.com/watch?v=_3GWeHB_bqk" }],
      materials: [],
    },
    {
      slug: "archivo-masterclass-07",
      kind: "masterclass",
      isArchive: true,
      title: "Colaboradores De Su Plan - Ger Páez",
      level: "free",
      short: "Jesús nos tomó y rescató para algo. Esto es, para colaborar con Su plan.",
      long: "Jesús nos tomó y rescató para algo. Esto es, para colaborar con Su plan. Él Espíritu Santo nos forja y forma a Cristo en nosotros para que aprendamos a ser como Él y poder ser buenos colaboradores de lo que Él está haciendo en la tierra. La unidad es una característica impresionante de Dios, y por lo tanto, también de Su Iglesia Gloriosa..",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/colaboradores.png",
      lessons: [{ title: "Masterclass", videoUrl: "https://www.youtube.com/watch?v=94XzMCi2v9U" }],
      materials: [],
    },
    {
      slug: "archivo-masterclass-08",
      kind: "masterclass",
      isArchive: true,
      title: "El liderazgo de Jesús en los Últimos Tiempos - Emiliano Rodriguez",
      level: "free",
      short: "Masterclass de años anteriores incorporada al archivo.",
      long: "Contenido de archivo disponible dentro de la biblioteca histórica de masterclasses.",
      price: 0,
      currency: "USD",
      thumbnail: "/assets/cursos/liderazgo.png",
      lessons: [{ title: "Masterclass", videoUrl: "https://www.youtube.com/watch?v=7ub_SJU4h98" }],
      materials: [],
    },
  ];

  await Course.deleteMany({});
  await Course.insertMany(data);

  console.log(`🌱 Seed OK: ${data.length} recursos insertados`);

  await mongoose.disconnect();
  console.log("🔌 Desconectado");
}

main().catch((err) => {
  console.error("❌ Seed error:", err);
  process.exit(1);
}); 